// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadCompactStartParams = { threadId: string,
/**
 * Optional instructions describing which context the compactor should prioritize.
 */
guidance?: string | null, };
