use std::collections::BTreeMap;

pub(super) fn known_issues() -> BTreeMap<&'static str, Vec<&'static str>> {
    BTreeMap::from([
        (
            "provider.tool_schema.custom_unsupported",
            vec![
                "https://github.com/openai/codex/issues/33405",
                "https://github.com/openai/codex/issues/37826",
            ],
        ),
        (
            "windows.sandbox.setup",
            vec![
                "https://github.com/openai/codex/issues/14585",
                "https://github.com/openai/codex/issues/31888",
            ],
        ),
        (
            "windows.sandbox.access_denied",
            vec![
                "https://github.com/openai/codex/issues/24214",
                "https://github.com/openai/codex/issues/31888",
            ],
        ),
        (
            "windows.sandbox.split_roots",
            vec![
                "https://github.com/openai/codex/issues/34088",
                "https://github.com/openai/codex/issues/35864",
            ],
        ),
        (
            "windows.sandbox.process_start",
            vec![
                "https://github.com/openai/codex/issues/30856",
                "https://github.com/openai/codex/issues/37919",
            ],
        ),
        (
            "file.apply_patch.failed",
            vec![
                "https://github.com/openai/codex/issues/24214",
                "https://github.com/openai/codex/issues/31776",
                "https://github.com/openai/codex/issues/30856",
            ],
        ),
        (
            "process.resource_sample",
            vec![
                "https://github.com/openai/codex/issues/12414",
                "https://github.com/openai/codex/issues/38877",
                "https://github.com/openai/codex/issues/29177",
                "https://github.com/openai/codex/issues/35823",
                "https://github.com/openai/codex/issues/16886",
            ],
        ),
    ])
}
